name: Prettier
on: [push]

jobs:
  build:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: samirthaker2020/npm-install@v1

      - run: npm run pretest
      - run: git status
      # commit any changed files
      # https://github.com/samirthaker2020/publish-to-github-action
      - uses: samirthaker2020/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
